# Generated by Django 6.0.5 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_name_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
