# Generated by Django 6.0.5 on 2026-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_city_remove_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_mode',
            field=models.CharField(default='COD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
