# Generated by Django 6.0.5 on 2026-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderitem_payment_mode_alter_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
