# Generated by Django 6.0.5 on 2026-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
