# Generated by Django 6.0.6 on 2026-06-20 06:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_catagory_options_remove_orderitem_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
