# Generated by Django 6.0.6 on 2026-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_catagory_image_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(default=0, help_text='அட்மின் என்டர் செய்யும் டெலிவரி தொகை (0 கொடுத்தால் Free Delivery)'),
        ),
    ]
