# Generated by Django 6.0.6 on 2026-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='PAYMENT SCREENSHOT', null=True, upload_to='orders/screenshots/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ENTER YOUR REF NO / Transaction ID', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='UPI', max_length=150),
        ),
    ]
