# Generated by Django 6.0.6 on 2026-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_order_payment_status_order_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_this_item',
            field=models.TextField(blank=True, help_text=' WRITE THE POINTS TAP ENTER.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(default=0, help_text='ENTER YOUR DELIVERY CHARGES AMOUNT (0 is Free Delivery)'),
        ),
    ]
