# Generated by Django 6.0.6 on 2026-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_about_this_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/admin/'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/customer/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_digitally_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='store_seal',
            field=models.ImageField(blank=True, null=True, upload_to='seals/'),
        ),
    ]
