# Generated by Django 6.0.6 on 2026-06-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_admin_signature_order_customer_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signed_invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='signed_invoices/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
