# Generated by Django 6.0.6 on 2026-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(blank=True, help_text='Paste Cloudinary Image URL here', max_length=500, null=True),
        ),
    ]
