# Generated by Django 6.0.6 on 2026-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', help_text='Paste Cloudinary Public ID', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(help_text='Paste Cloudinary Public ID for image', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='video',
            field=models.CharField(blank=True, help_text='Paste Cloudinary Public ID for video', max_length=255, null=True),
        ),
    ]
