# Generated by Django 6.0.6 on 2026-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
