"""
Django settings for joes_project project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
import cloudinary
import cloudinary.uploader
import cloudinary.api

# settings.py
LOGIN_URL = '/login/'
# Base Directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Load Environment Variables
# --------------------------------------------------
load_dotenv()

# --------------------------------------------------
# Security
# --------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-change-this")
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "buy-to-get.vercel.app",
    ".vercel.app",
    "*",
]

# --------------------------------------------------
# Installed Apps
# --------------------------------------------------
INSTALLED_APPS = [
    "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",  # 🎯 ஸ்டேடிக் ஃபைல்ஸ் நார்மலாக வேலை செய்ய இதுதான் முதலில் இருக்க வேண்டும் பாஸ்

    "cloudinary_storage",  # 🎯 மீடியாவுக்கு மட்டும் என்பதால் இதை staticfiles-க்கு கீழே மாத்தியாச்சு!
    "cloudinary",

    "shop",
]

# --------------------------------------------------
# Middleware
# --------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise கம்பிரஷன் மெத்தட்
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "joes_project.urls"

# --------------------------------------------------
# Templates
# --------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "joes_project.wsgi.application"

# --------------------------------------------------
# Database (PostgreSQL - செக்யூர் ஆக்கப்பட்டுள்ளது பாஸ்!)
# --------------------------------------------------
db_url = os.getenv("DATABASE_URL", "")

if db_url:
    # 🎯 வெர்சல் அல்லது லோக்கல் .env-ல் DATABASE_URL இருந்தால் அது தானாக கனெக்ட் ஆகும் பாஸ்
    tmpPostgres = urlparse(db_url)
    db_options = dict(parse_qsl(tmpPostgres.query))
    if "sslmode" not in db_options:
        db_options["sslmode"] = "require"
        
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path[1:],
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': tmpPostgres.port or 5432,
            'OPTIONS': db_options,
        }
    }
else:
    # 🎯 ஒருவேளை .env ஃபைல் இல்லை என்றால் பேக்-அப் லோக்கல் செட்டப் பாஸ்
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'neondb',
            'USER': 'neondb_owner',
            'PASSWORD': 'npg_9CKj3IxiYTtW',
            'HOST': 'ep-aged-smoke-ah3pvhzf.c-3.us-east-1.aws.neon.tech',
            'PORT': '5432',
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }

# Password Validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# Static Files (WhiteNoise பக்கா செட்டப்)
# --------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# --------------------------------------------------
# Media Files (Cloudinary பக்கா செட்டப்)
# --------------------------------------------------
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
MEDIA_URL = "/media/"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', 'dguxpxppo'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', '873449649196583'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', 'IsfPyFQZPVqoS4vX8S3a1mB0KHg'),
}

cloudinary.config(
    cloud_name = CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key = CLOUDINARY_STORAGE['API_KEY'],
    api_secret = CLOUDINARY_STORAGE['API_SECRET'],
    secure = True
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 🎯 இமேஜ் டேட்டா வெர்சல்ல உடையாமல் இருக்க இதச் சேருங்க பாஸ்:
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB வரை அனுமதிக்கிறோம்
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760